export interface FanGuideEntry {
  fanKey: string;
  fanValue: number;
  label: string;
  intro: string;
  example: string;
}

const FAN_GUIDE_DEFINITIONS: Array<Omit<FanGuideEntry, 'label'>> = [
  {
    fanKey: 'self_drawn',
    fanValue: 1,
    intro: '和牌张由自己从牌墙摸入，不是吃碰别人打出的牌。',
    example: '听牌后自己摸到需要的那一张完成和牌。',
  },
  {
    fanKey: 'pure_double_chow',
    fanValue: 1,
    intro: '同一花色里出现两副完全相同的顺子。',
    example: '123万、123万，再配其余面子与将牌。',
  },
  {
    fanKey: 'mixed_double_chow',
    fanValue: 1,
    intro: '两副点数相同、花色不同的顺子。',
    example: '123万、123筒，再配其余面子与将牌。',
  },
  {
    fanKey: 'short_straight',
    fanValue: 1,
    intro: '同一花色里两副相连的顺子，合起来是六张连续牌。',
    example: '123条、456条。',
  },
  {
    fanKey: 'two_terminal_chows',
    fanValue: 1,
    intro: '同一花色里同时有 123 和 789 两副顺子。',
    example: '123筒、789筒。',
  },
  {
    fanKey: 'one_voided_suit',
    fanValue: 1,
    intro: '和牌时三种数牌里缺少其中一门。',
    example: '整手牌只用万子和条子，没有任何筒子。',
  },
  {
    fanKey: 'no_honours',
    fanValue: 1,
    intro: '整手和牌中没有任何字牌。',
    example: '全部由万、筒、条组成，没有风牌和箭牌。',
  },
  {
    fanKey: 'pung_of_terminals_or_honours',
    fanValue: 1,
    intro: '包含 1、9 数牌刻子或任意字牌刻子。',
    example: '111万、999筒，或东东东。',
  },
  {
    fanKey: 'melded_kong',
    fanValue: 1,
    intro: '通过碰后加杠，或直接明杠形成的杠子。',
    example: '先碰 5 条，再补成 5555 条明杠。',
  },
  {
    fanKey: 'edge_wait',
    fanValue: 1,
    intro: '和牌时等的是 3 组成 123，或等的是 7 组成 789。',
    example: '手里有 12万，等 3万；或有 89筒，等 7筒。',
  },
  {
    fanKey: 'closed_wait',
    fanValue: 1,
    intro: '和牌时等的是顺子中间那张牌。',
    example: '手里有 24条，等 3条。',
  },
  {
    fanKey: 'single_wait',
    fanValue: 1,
    intro: '和牌时只等将牌那一张。',
    example: '四副面子已齐，只差一张 5筒 配成 55筒。',
  },
  {
    fanKey: 'flower_tiles',
    fanValue: 1,
    intro: '每有一张花牌就额外计 1 番。',
    example: '和牌时手中有春、夏、秋、冬中的任意花牌。',
  },
  {
    fanKey: 'all_simples',
    fanValue: 2,
    intro: '整手牌不含 1、9 和字牌。',
    example: '全部由 2 到 8 的数牌组成。',
  },
  {
    fanKey: 'ready_hand_win',
    fanValue: 2,
    intro: '和牌前已经正式宣告听牌，最终以该局听牌状态完成和牌。',
    example: '点击“听”后锁手，之后自摸或荣和完成本局和牌。',
  },
  {
    fanKey: 'seat_wind',
    fanValue: 2,
    intro: '有一副与自己门风相同的风牌刻子。',
    example: '自己坐东位，和牌中有东东东。',
  },
  {
    fanKey: 'prevalent_wind',
    fanValue: 2,
    intro: '有一副与当前圈风相同的风牌刻子。',
    example: '南圈时，和牌中有南南南。',
  },
  {
    fanKey: 'dragon_pung',
    fanValue: 2,
    intro: '有中、发、白任意一种箭牌刻子。',
    example: '中中中 或 白白白。',
  },
  {
    fanKey: 'double_pung',
    fanValue: 2,
    intro: '不同花色里有两副点数相同的刻子。',
    example: '555万、555筒。',
  },
  {
    fanKey: 'two_concealed_pungs',
    fanValue: 2,
    intro: '有两副暗刻，且不是通过吃碰明露出来的。',
    example: '手中原生形成 333万、777条。',
  },
  {
    fanKey: 'tile_hog',
    fanValue: 2,
    intro: '某一种牌出现四张，但没有组成杠，而是分散用于顺子、刻子或将。',
    example: '4 张 5万 分别落在 345万、567万 与 55万 中。',
  },
  {
    fanKey: 'concealed_kong',
    fanValue: 2,
    intro: '四张同牌全部由自己持有并直接暗杠。',
    example: '手中自成 7777筒 暗杠。',
  },
  {
    fanKey: 'all_chows',
    fanValue: 2,
    intro: '和牌由四副顺子和一对将组成，不含任何刻子。',
    example: '123万、456万、234条、678筒、55条。',
  },
  {
    fanKey: 'concealed_hand',
    fanValue: 2,
    intro: '整手牌在和牌前未吃碰明露，保持门前状态。',
    example: '始终不吃不碰，靠自摸或荣和完成和牌。',
  },
  {
    fanKey: 'two_melded_kongs',
    fanValue: 4,
    intro: '和牌中共有两副明杠。',
    example: '1111万 和 7777筒 都以明杠方式成立。',
  },
  {
    fanKey: 'outside_hand',
    fanValue: 4,
    intro: '每一副面子和将牌都至少含有 1、9 或字牌。',
    example: '123万、789筒、东东东、999条、白白。',
  },
  {
    fanKey: 'fully_concealed_hand',
    fanValue: 4,
    intro: '全程门前清并以自摸方式和牌。',
    example: '不吃不碰不明杠，最后自摸和牌。',
  },
  {
    fanKey: 'last_tile',
    fanValue: 4,
    intro: '和的是场上最后一张可用牌，也就是绝张。',
    example: '前三张 8条 已全部出现，第 4 张 8条 被用来和牌。',
  },
  {
    fanKey: 'half_flush',
    fanValue: 6,
    intro: '整手牌由一种数牌和字牌组成。',
    example: '全部是万子加风牌、箭牌。',
  },
  {
    fanKey: 'two_dragon_pungs',
    fanValue: 6,
    intro: '同时有两种箭牌刻子。',
    example: '中中中 加 发发发。',
  },
  {
    fanKey: 'all_pungs',
    fanValue: 6,
    intro: '四副面子全部都是刻子或杠子。',
    example: '111万、999万、555筒、东东东、66条。',
  },
  {
    fanKey: 'all_types',
    fanValue: 6,
    intro: '和牌同时包含万、筒、条三门数牌，以及风牌、箭牌。',
    example: '手里同时出现万子、筒子、条子、东南西北与中发白中的牌。',
  },
  {
    fanKey: 'mixed_shifted_chows',
    fanValue: 6,
    intro: '三种花色里有三副依次递进的顺子。',
    example: '123万、234筒、345条。',
  },
  {
    fanKey: 'melded_hand',
    fanValue: 6,
    intro: '和牌前四副面子都已吃碰明露，只剩单钓将。',
    example: '吃碰出四组面子后，手里只等一张将牌。',
  },
  {
    fanKey: 'out_with_replacement_tile',
    fanValue: 8,
    intro: '杠后补牌时，补进来的那张正好和牌。',
    example: '开杠补牌摸进和牌张。',
  },
  {
    fanKey: 'last_tile_draw',
    fanValue: 8,
    intro: '摸到牌墙最后一张牌并自摸和牌。',
    example: '海底最后一张牌被自己摸起完成和牌。',
  },
  {
    fanKey: 'last_tile_claim',
    fanValue: 8,
    intro: '别人打出牌墙最后一张牌，被你荣和。',
    example: '海底最后一张舍牌刚好点中你。',
  },
  {
    fanKey: 'robbing_the_kong',
    fanValue: 8,
    intro: '别人加杠时，你用那张被加上的牌直接和牌。',
    example: '对手碰了 6万 后补杠，你以那张 6万 抢杠和。',
  },
  {
    fanKey: 'mixed_shifted_pungs',
    fanValue: 8,
    intro: '三种花色里有三副依次递进的刻子。',
    example: '333万、444筒、555条。',
  },
  {
    fanKey: 'reversible_tiles',
    fanValue: 8,
    intro: '整手牌只由推不倒牌张构成，牌面上下颠倒看仍对称。',
    example: '只用 1234589筒、245689条 和白板组成和牌。',
  },
  {
    fanKey: 'mixed_triple_chow',
    fanValue: 8,
    intro: '三种花色里各有一副点数完全相同的顺子。',
    example: '456万、456筒、456条。',
  },
  {
    fanKey: 'mixed_straight',
    fanValue: 8,
    intro: '三种花色分别凑成 123、456、789 这三段连续结构。',
    example: '123万、456筒、789条。',
  },
  {
    fanKey: 'two_concealed_kongs',
    fanValue: 8,
    intro: '和牌中有两副暗杠。',
    example: '1111万 与 9999条 都由自己暗杠。',
  },
  {
    fanKey: 'chicken_hand',
    fanValue: 8,
    intro: '除花牌外没有任何其他番型时，以鸡和计番。',
    example: '和牌结构普通，未构成其他番种。',
  },
  {
    fanKey: 'knitted_straight',
    fanValue: 12,
    intro: '由三门花色的 147、258、369 组合成完整的组合龙。',
    example: '147万、258筒、369条，再配一副面子和一对将。',
  },
  {
    fanKey: 'lesser_honours_and_knitted_tiles',
    fanValue: 12,
    intro: '和牌由互不相连的数牌与部分字牌组成，整体不靠张。',
    example: '147万、258筒、369条，加 5 张互不重复的字牌。',
  },
  {
    fanKey: 'big_three_winds',
    fanValue: 12,
    intro: '有三副不同风牌刻子。',
    example: '东东东、南南南、西西西。',
  },
  {
    fanKey: 'upper_four',
    fanValue: 12,
    intro: '整手牌只用 6 到 9 的数牌组成。',
    example: '678万、789万、888筒、999条、66筒。',
  },
  {
    fanKey: 'lower_four',
    fanValue: 12,
    intro: '整手牌只用 1 到 4 的数牌组成。',
    example: '123万、234筒、111条、444万、22筒。',
  },
  {
    fanKey: 'triple_pung',
    fanValue: 16,
    intro: '三种花色里各有一副点数相同的刻子。',
    example: '777万、777筒、777条。',
  },
  {
    fanKey: 'three_concealed_pungs',
    fanValue: 16,
    intro: '和牌里有三副暗刻。',
    example: '手中原生形成 222万、555筒、999条。',
  },
  {
    fanKey: 'all_fives',
    fanValue: 16,
    intro: '每一副面子和将牌都至少包含数字 5。',
    example: '345万、555筒、456条、678万、55筒。',
  },
  {
    fanKey: 'pure_straight',
    fanValue: 16,
    intro: '同一花色里同时有 123、456、789 三副顺子。',
    example: '123万、456万、789万。',
  },
  {
    fanKey: 'pure_shifted_chows',
    fanValue: 16,
    intro: '同一花色里有三副依次递进的顺子。',
    example: '123筒、234筒、345筒。',
  },
  {
    fanKey: 'three_suited_terminal_chows',
    fanValue: 16,
    intro: '两门花色分别有老少副，第三门以 5 作将牌。',
    example: '123万、789万、123筒、789筒、55条。',
  },
  {
    fanKey: 'full_flush',
    fanValue: 24,
    intro: '整手牌只由同一种数牌组成，不含字牌。',
    example: '全部都是条子，没有万、筒和字牌。',
  },
  {
    fanKey: 'seven_pairs',
    fanValue: 24,
    intro: '和牌由七个对子组成。',
    example: '11万、22万、33筒、44筒、55条、66条、东东。',
  },
  {
    fanKey: 'greater_honours_and_knitted_tiles',
    fanValue: 24,
    intro: '七星不靠，需要七种字牌与互不相连的数牌共同组成。',
    example: '147万、258筒、369条，加东南西北中发白。',
  },
  {
    fanKey: 'all_even_pungs',
    fanValue: 24,
    intro: '整手牌由偶数牌刻子组成，且没有字牌。',
    example: '222万、444万、666筒、888条、22筒。',
  },
  {
    fanKey: 'upper_tiles',
    fanValue: 24,
    intro: '整手牌只用 7、8、9 的数牌组成。',
    example: '789万、777筒、888条、999万、77条。',
  },
  {
    fanKey: 'lower_tiles',
    fanValue: 24,
    intro: '整手牌只用 1、2、3 的数牌组成。',
    example: '123万、111筒、222条、333万、11条。',
  },
  {
    fanKey: 'middle_tiles',
    fanValue: 24,
    intro: '整手牌只用 4、5、6 的数牌组成。',
    example: '456万、444筒、555条、666万、44条。',
  },
  {
    fanKey: 'pure_shifted_pungs',
    fanValue: 24,
    intro: '同一花色里有三副依次递进的刻子。',
    example: '333万、444万、555万。',
  },
  {
    fanKey: 'pure_triple_chow',
    fanValue: 24,
    intro: '同一花色里出现三副完全相同的顺子。',
    example: '456条、456条、456条。',
  },
  {
    fanKey: 'all_terminals_and_honours',
    fanValue: 32,
    intro: '整手牌只由 1、9 和字牌组成。',
    example: '111万、999筒、东东东、中中中、99条。',
  },
  {
    fanKey: 'four_pure_shifted_chows',
    fanValue: 32,
    intro: '同一花色里有四副依次递进的顺子。',
    example: '123万、234万、345万、456万。',
  },
  {
    fanKey: 'three_kongs',
    fanValue: 32,
    intro: '和牌中共有三副杠子。',
    example: '1111万、5555筒、9999条，再配其余结构和牌。',
  },
  {
    fanKey: 'four_pure_shifted_pungs',
    fanValue: 48,
    intro: '同一花色里有四副依次递进的刻子。',
    example: '222筒、333筒、444筒、555筒。',
  },
  {
    fanKey: 'quadruple_chow',
    fanValue: 48,
    intro: '同一花色里出现四副完全相同的顺子。',
    example: '123条、123条、123条、123条。',
  },
  {
    fanKey: 'little_three_dragons',
    fanValue: 64,
    intro: '两副箭牌刻子加上一对第三种箭牌。',
    example: '中中中、发发发、白白。',
  },
  {
    fanKey: 'little_four_winds',
    fanValue: 64,
    intro: '三副风牌刻子加上一对第四种风牌。',
    example: '东东东、南南南、西西西、北北。',
  },
  {
    fanKey: 'all_honours',
    fanValue: 64,
    intro: '整手牌全部由风牌和箭牌组成。',
    example: '东东东、南南南、西西西、中中中、白白。',
  },
  {
    fanKey: 'four_concealed_pungs',
    fanValue: 64,
    intro: '和牌里有四副暗刻。',
    example: '四组刻子全部靠自己摸成，未吃碰明露。',
  },
  {
    fanKey: 'pure_terminal_chows',
    fanValue: 64,
    intro: '同一花色内两组 123、两组 789，再配 5 作将。',
    example: '123万、123万、789万、789万、55万。',
  },
  {
    fanKey: 'thirteen_orphans',
    fanValue: 88,
    intro: '由 1、9 各门数牌与七种字牌各一张，再加其中任意一张配对组成。',
    example: '1万、9万、1筒、9筒、1条、9条、东南西北中发白，再加任意一张作将。',
  },
  {
    fanKey: 'seven_shifted_pairs',
    fanValue: 88,
    intro: '同一花色内七个连续对子组成和牌。',
    example: '11万、22万、33万、44万、55万、66万、77万。',
  },
  {
    fanKey: 'nine_gates',
    fanValue: 88,
    intro: '同一花色里以 1112345678999 为骨架，再加该门任意一张和牌。',
    example: '1112345678999条，加任意一张条子。',
  },
  {
    fanKey: 'big_three_dragons',
    fanValue: 88,
    intro: '中、发、白三种箭牌全部成刻。',
    example: '中中中、发发发、白白白。',
  },
  {
    fanKey: 'big_four_winds',
    fanValue: 88,
    intro: '东南西北四种风牌全部成刻。',
    example: '东东东、南南南、西西西、北北北。',
  },
  {
    fanKey: 'all_terminals',
    fanValue: 88,
    intro: '整手牌只由 1 和 9 的数牌组成，不含字牌。',
    example: '111万、999万、111筒、999筒、11条。',
  },
  {
    fanKey: 'all_green',
    fanValue: 88,
    intro: '整手牌只由绿色牌张组成。',
    example: '23468条、发发发 这些绿色牌张构成和牌。',
  },
  {
    fanKey: 'four_kongs',
    fanValue: 88,
    intro: '和牌中共有四副杠子。',
    example: '四组同牌都已经成杠，再配一对将牌。',
  },
];

export const FAN_LABELS: Record<string, string> = {
  self_drawn: '自摸',
  pure_double_chow: '一般高',
  mixed_double_chow: '喜相逢',
  short_straight: '连六',
  two_terminal_chows: '老少副',
  one_voided_suit: '缺一门',
  no_honours: '无字',
  pung_of_terminals_or_honours: '幺九刻',
  melded_kong: '明杠',
  edge_wait: '边张',
  closed_wait: '嵌张',
  single_wait: '单钓将',
  flower_tiles: '花牌',
  all_simples: '断幺',
  ready_hand_win: '听牌成和',
  seat_wind: '门风刻',
  prevalent_wind: '圈风刻',
  dragon_pung: '箭刻',
  double_pung: '双同刻',
  two_concealed_pungs: '双暗刻',
  tile_hog: '四归一',
  concealed_kong: '暗杠',
  all_chows: '平和',
  concealed_hand: '门前清',
  two_melded_kongs: '双明杠',
  outside_hand: '全带幺',
  fully_concealed_hand: '不求人',
  last_tile: '和绝张',
  half_flush: '混一色',
  two_dragon_pungs: '双箭刻',
  all_pungs: '对对和',
  all_types: '五门齐',
  mixed_shifted_chows: '三色三步高',
  melded_hand: '全求人',
  out_with_replacement_tile: '杠上开花',
  last_tile_draw: '妙手回春',
  last_tile_claim: '海底捞月',
  robbing_the_kong: '抢杠和',
  mixed_shifted_pungs: '三色三节高',
  reversible_tiles: '推不倒',
  mixed_triple_chow: '三色三同顺',
  mixed_straight: '花龙',
  two_concealed_kongs: '双暗杠',
  chicken_hand: '鸡和',
  knitted_straight: '组合龙',
  lesser_honours_and_knitted_tiles: '全不靠',
  big_three_winds: '三风刻',
  upper_four: '大于五',
  lower_four: '小于五',
  triple_pung: '三色三同刻',
  three_concealed_pungs: '三暗刻',
  all_fives: '全带五',
  pure_straight: '一条龙',
  pure_shifted_chows: '一色三步高',
  three_suited_terminal_chows: '三色双龙会',
  full_flush: '清一色',
  seven_pairs: '七对',
  greater_honours_and_knitted_tiles: '七星不靠',
  all_even_pungs: '全双刻',
  upper_tiles: '全大',
  lower_tiles: '全小',
  middle_tiles: '全中',
  pure_shifted_pungs: '一色三节高',
  pure_triple_chow: '一色三同顺',
  all_terminals_and_honours: '混幺九',
  four_pure_shifted_chows: '一色四步高',
  three_kongs: '三杠',
  four_pure_shifted_pungs: '一色四节高',
  quadruple_chow: '一色四同顺',
  little_three_dragons: '小三元',
  little_four_winds: '小四喜',
  all_honours: '字一色',
  four_concealed_pungs: '四暗刻',
  pure_terminal_chows: '一色双龙会',
  thirteen_orphans: '十三幺',
  seven_shifted_pairs: '连七对',
  nine_gates: '九莲宝灯',
  big_three_dragons: '大三元',
  big_four_winds: '大四喜',
  all_terminals: '清幺九',
  all_green: '绿一色',
  four_kongs: '四杠',
  self_draw: '自摸',
  zi_mo: '自摸',
  ping_hu: '平和',
  men_qian_qing: '门前清',
  all_terminals_or_honours: '混幺九',
  all_honors: '字一色',
  heavenly_hand: '天和',
  earthly_hand: '地和',
  human_hand: '人和',
};

export const FAN_GUIDE_ENTRIES: FanGuideEntry[] = FAN_GUIDE_DEFINITIONS.map((entry) => ({
  ...entry,
  label: getFanLabel(entry.fanKey),
}));

const FAN_GUIDE_ENTRY_MAP = new Map(FAN_GUIDE_ENTRIES.map((entry) => [entry.fanKey, entry]));

const FAN_GUIDE_KEY_ALIASES: Record<string, string> = {
  self_draw: 'self_drawn',
  zi_mo: 'self_drawn',
  ping_hu: 'all_chows',
  men_qian_qing: 'concealed_hand',
  all_terminals_or_honours: 'all_terminals_and_honours',
  all_honors: 'all_honours',
};

export function getFanLabel(fanKey: string) {
  return FAN_LABELS[fanKey] ?? fanKey;
}

export function getFanGuideEntry(fanKey: string) {
  return FAN_GUIDE_ENTRY_MAP.get(FAN_GUIDE_KEY_ALIASES[fanKey] ?? fanKey) ?? null;
}
